"""budgets and reports

Revision ID: 0b733c0b57e3
Revises: cecb48c9cea2
Create Date: 2026-07-24 15:43:26.673247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b733c0b57e3'
down_revision: Union[str, None] = 'cecb48c9cea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_budget_category')
    )
    op.create_table('budget_amounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['budget_category_id'], ['budget_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_category_id', 'year', 'month', name='uq_budget_amount_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_amounts')
    op.drop_table('budget_categories')
    op.drop_table('budgets')
    # ### end Alembic commands ###
