"""add category is_income flag

Revision ID: 2505b64e181c
Revises: 44fdb4c3ba29
Create Date: 2026-07-29 18:58:51.956713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2505b64e181c'
down_revision: Union[str, None] = '44fdb4c3ba29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_income', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_income')
    # ### end Alembic commands ###
