"""change history and app settings

Revision ID: 44fdb4c3ba29
Revises: 9224ce5f35e7
Create Date: 2026-07-28 20:05:07.914295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fdb4c3ba29'
down_revision: Union[str, None] = '9224ce5f35e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperation'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_changes_created_at'), 'account_changes', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_changes_entity_id'), 'account_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_account_changes_group_id'), 'account_changes', ['group_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperation'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_changes_created_at'), 'category_changes', ['created_at'], unique=False)
    op.create_index(op.f('ix_category_changes_entity_id'), 'category_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_category_changes_group_id'), 'category_changes', ['group_id'], unique=False)
    op.create_table('transaction_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperation'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_changes_created_at'), 'transaction_changes', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_changes_entity_id'), 'transaction_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_transaction_changes_group_id'), 'transaction_changes', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_changes_group_id'), table_name='transaction_changes')
    op.drop_index(op.f('ix_transaction_changes_entity_id'), table_name='transaction_changes')
    op.drop_index(op.f('ix_transaction_changes_created_at'), table_name='transaction_changes')
    op.drop_table('transaction_changes')
    op.drop_index(op.f('ix_category_changes_group_id'), table_name='category_changes')
    op.drop_index(op.f('ix_category_changes_entity_id'), table_name='category_changes')
    op.drop_index(op.f('ix_category_changes_created_at'), table_name='category_changes')
    op.drop_table('category_changes')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_account_changes_group_id'), table_name='account_changes')
    op.drop_index(op.f('ix_account_changes_entity_id'), table_name='account_changes')
    op.drop_index(op.f('ix_account_changes_created_at'), table_name='account_changes')
    op.drop_table('account_changes')
    # ### end Alembic commands ###
