"""rules and suggestion fields

Revision ID: cecb48c9cea2
Revises: 91448d80f8e3
Create Date: 2026-07-24 15:32:33.573360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecb48c9cea2'
down_revision: Union[str, None] = '91448d80f8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('ANY', 'ALL', name='matchtype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.Enum('DATE', 'DAY_OF_MONTH', 'NAME', 'ACCOUNT', 'AMOUNT', name='conditionfield'), nullable=False),
    sa.Column('operator', sa.Enum('CONTAINS', 'NOT_CONTAINS', 'EQUALS', 'LESS_THAN', 'GREATER_THAN', name='conditionoperator'), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite can't ALTER to add a constraint directly; batch mode recreates
    # the table under the hood to add the new columns + FK together.
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('suggestion_source', sa.Enum('RULE', 'AI', name='suggestionsource'), nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_splits_suggested_category_id', 'categories', ['suggested_category_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('splits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_splits_suggested_category_id', type_='foreignkey')
        batch_op.drop_column('suggestion_source')
        batch_op.drop_column('suggested_category_id')
    op.drop_table('rule_conditions')
    op.drop_table('rules')
    # ### end Alembic commands ###
